debug = true
disable-ads = false

replacer-basic = [ "|twitter.com|nitter.net" ]
replacer-regex = ['''%.*(youtu\.be/|youtube\.com/watch\?v=)([a-zA-Z0-9_]+).*%https://youtube.com/embed/$2
https://i.ytimg.com/vi/$2/hqdefault.jpg''']

filter-conv = [
  "0000d7cf1e6f51d75f9a354c2cb7c3bd30415f184bbb9eba0c57aa50827b7663",
  "0000d0cf70804671490e7f8f21c207a1ac6a8bc2ee05db804fb4531ab6c06f05",
]